# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/db/schema.rs"
generate_missing_sql_type_definitions = true
custom_type_derives = ["diesel::sql_types::SqlType", "std::fmt::Debug"]
